# Generated by Django 4.2.6 on 2023-10-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('closing_date', models.DateField()),
            ],
        ),
    ]
